---
title: "TGI Spinal Data Compiler"
author: "A.G. Mitchell"
date: "2022-12-02"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Loading libraries
# check for pacman package and install if not found
if (!require("pacman")) install.packages("pacman")
  pacman::p_load(boot, broom, broom.mixed, brms, car, caret, corrplot, DHARMa, gamlss,
                 ggeffects, gghalves, ggpol, ggpubr, glmmTMB, groupdata2, lme4, lmerTest, 
                 modelsummary, MuMIn, polycor, RColorBrewer, rcompanion, reshape2, Rmisc,
                 rsample, rstatix, simr, tibble, tidyverse, wesanderson
                 )
```

To compile all the raw data, need to access paths in directory
This is done for experiment 1 first, then experiment 2

```{r paths}
# paths
exp1Path <- '/Users/au706616/Documents/Experiments/SPINALTGI/exp1/Raw/'
exp2Path <- '/Users/au706616/Documents/Experiments/SPINALTGI/exp2/Raw/'
```

# EXPERIMENT 1 DATA
```{r data, echo = FALSE}
# Extract all .csv files and compile
filenames <- dir(exp1Path, recursive = TRUE, full.names = FALSE, pattern = '.csv')
# empty dataframes for data
## with new data trials file will have changed to include temperature coding!
df_trials <- read.csv(text='procedure,trial_type,arm,condition,dermatome,order,cold_probe,trial_n,coolTemp,warmTempID,manipulation')
df_VAS <- read.csv(text='VASinit,VASburn,VASwarm,VAScold,trial_n,ID,manipulation')
df_RT <- read.csv(text='RTinit,RTburn,RTwarm,RTcold,trial_n,ID,manipulation')

## Data compiling
# trial files
setwd(exp1Path)
for (file in filenames){
  # trial files
  if (isTRUE(substr(basename(file), 24, 24)=="t")){
    tmp <- read.csv(file)
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_trials <- rbind(df_trials, tmp)
  }
  # VAS response files
  if (isTRUE(substr(basename(file), 24, 29)=="rating")){
    tmp <- read.csv(file, header = FALSE)
    colnames(tmp) <- c('VASinit','VASburn','VASwarm','VAScold','trial_n')
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_VAS <- rbind(df_VAS, tmp)
  }
  # VAS RT files
  if (isTRUE(substr(basename(file), 24, 29)=="respti")){
    tmp <- read.csv(file, header = FALSE)
    colnames(tmp) <- c('RTinit','RTburn','RTwarm','RTcold','trial_n')
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_RT <- rbind(df_RT, tmp)
  }
}

# merge all files
df_res <- merge(df_trials, df_VAS, by = c('ID','trial_n','manipulation'))
df_res <- merge(df_res, df_RT, by = c('ID','trial_n','manipulation'))
```
# dData organisation
```{r}
# remove participant 019, stopped testing halfway due to broken thermal probe
df_res <- df_res[df_res$ID != '019' ,]

# transform the ID of participants to remove 0
df_res$ID <- as.numeric(df_res$ID)
# recode conditions
df_res <- df_res %>%
  mutate(condition = dplyr::recode(condition, '1' = 'within', '2' = 'across'),
         cold_probe = dplyr::recode(cold_probe, 'C6' = 'rostral', 'T1' = 'caudal',
                             'dist' = 'distal', 'prox' = 'proximal'))
# change levels 
df_res$cold_probe <- factor(df_res$cold_probe, 
                            levels = c("caudal", "rostral", "distal", "proximal"))

```

# Merge with demographics
```{r}
# incorporate demographics
# the warm and cold TGI and CNT temperatures did not code properly on the trial .csv
# have saved these in the demo .csv as well, so will add these in
demoFile <- 'STGI_exp1_participant-demographics.csv'
fileName = paste(exp1Path, demoFile, sep = '')
df_demo <- read.csv(fileName)
# merge
df_res <- merge(df_res, df_demo)
df_res <- df_res %>% 
  select(-c(warmT, coldT, Tested, Calibration, Notes))

# save new data-frame
write.csv(df_res, file.path("data", "STGI_exp1_compiled-data.csv"), row.names = FALSE)

# check we have 40 participants with 96 trials
id_check <- count(df_res, ID)
id_check
```


Do the same for experiment 2
# EXPERIMENT 2 LOAD DATA
```{r data, echo = FALSE}
# Extract all .csv files and compile
filenames <- dir(exp2Path, recursive = TRUE, full.names = FALSE, pattern = '.csv')
# empty dataframes for data
## with new data trials file will have changed to include temperature coding!
df_trials <- read.csv(text='procedure,trial_type,arm,condition,dermatome,order,cold_probe,trial_n,coolTemp,warmTempID,manipulation')
df_VAS <- read.csv(text='VASinit,VASburn,VASwarm,VAScold,trial_n,ID,manipulation')
df_RT <- read.csv(text='RTinit,RTburn,RTwarm,RTcold,trial_n,ID,manipulation')

## Data compiling
# trial files
setwd(exp2Path)
for (file in filenames){
  # trial files
  if (isTRUE(substr(basename(file), 24, 24)=="t")){
    tmp <- read.csv(file)
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_trials <- rbind(df_trials, tmp)
  }
  # VAS response files
  if (isTRUE(substr(basename(file), 24, 29)=="rating")){
    tmp <- read.csv(file, header = FALSE)
    colnames(tmp) <- c('VASinit','VASburn','VASwarm','VAScold','trial_n')
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_VAS <- rbind(df_VAS, tmp)
  }
  # VAS RT files
  if (isTRUE(substr(basename(file), 24, 29)=="respti")){
    tmp <- read.csv(file, header = FALSE)
    colnames(tmp) <- c('RTinit','RTburn','RTwarm','RTcold','trial_n')
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_RT <- rbind(df_RT, tmp)
  }
}

# merge all files
df_res <- merge(df_trials, df_VAS, by = c('ID','trial_n','manipulation'))
df_res <- merge(df_res, df_RT, by = c('ID','trial_n','manipulation'))
```

# Data organisation
```{r}
# remove participants 047 and 048
# one had ongoing pain, the other missed 6 trials
df_res <- df_res[df_res$ID != '047' ,]
df_res <- df_res[df_res$ID != '048' ,]

# transform the ID of participants to remove 0
df_res$ID <- as.numeric(df_res$ID)
# recode conditions
df_res <- df_res %>%
  mutate(condition = dplyr::recode(condition, '1' = 'within', '2' = 'across'),
         cold_probe = dplyr::recode(cold_probe, 'C6' = 'rostral', 'T1' = 'caudal',
                             'dist' = 'distal', 'prox' = 'proximal'))
# change levels 
df_res$cold_probe <- factor(df_res$cold_probe, 
                            levels = c("caudal", "rostral", "distal", "proximal"))
```

# Merge with demographics
```{r}
# incorporate demographics
# the warm and cold TGI and CNT temperatures did not code properly on the trial .csv
# have saved these in the demo .csv as well, so will add these in
demoFile <- 'STGI_exp2_participant-demographics.csv'
fileName = paste(exp2Path, demoFile, sep = '')
df_demo <- read.csv(fileName)
# merge
df_res <- merge(df_res, df_demo)
df_res <- df_res %>% 
  select(-c(warmTGI, coldTGI, Tested, Calibration, Notes))

# save new data-frame
write.csv(df_res, file.path("data", "STGI_exp1_compiled-data.csv"), row.names = FALSE)

# check we have 40 participants with 96 trials
id_check <- count(df_res, ID)
id_check
```
