%% Instructions for VAS_run.m in Danish
% JF Ehmsen, DE Christensen
% 23.06.22
%% Variables
vars.instructions.StartScreen = ['For hver runde vil du mærke termisk stimulation.\n\n' ...
    'I starten af hver stimulation og runde, bedes du vurdere den mest intense brændende følelese du\n' ...
    'mærker fra enten holder A eller B på en skala fra 0 - 100.\n\n' ...
    'Efter dette, skal du vurdere hvor brændende, varm og kold som holder A eller B er,\n' ...
    'på en skala fra 0 - 100.\n\n' ...
    '0 betyder at det ikke føles brændende/varmt/koldt, og 100 betyder at det føles ekstremt brændende/varmt/koldt.\n'...
    'Venligst brug hele skalaen, og svar 0, hvis du ikke føler noget af det ovenstående.\n\n'...
    'Det er vigtigt at du vurderer den følelse du føler i det sekund du svarer, fra den holder\n'...
    'som du specifikt er blevet instrueret i at skulle have fokus på af forskningsassistenten.\n\n' ...
    'Når du er klar, tryk på en vilkårlig tast for at gå i gang.'];

vars.instructions.StartVas = ['Efter instruks af forskningsassistenten, tryk på en tast, for at starte med at vurdere.\n\n' ...
    'Når du er færdig, tryk på MELLEMRUM, for at fortsætte til næste vurdering.'];

vas.instructions.Calib = ['Du skal nu, vurdere hvor meget stimulationen føles BRÆNDENDE.\n\n' ...
    'Du bedes svare ærligt og giv enhver tilbagemelding vedrørende din oplevelse/følelse til assistenten.'];
% 
% vars.instructions.Question = {'På nuværende tidpsunkt, hvor stærk er den stærkeste BRÆNDENDE følelse?',...
%                                'På nuværende tidpsunkt, hvor BRÆNDENDE føles stimulutionen?',...
%                                'På nuværende tidpsunkt, hvor VARM føles stimulutionen?',...
%                                'På nuværende tidpsunkt, hvor KOLD føles stimulutionen?' }; 
 vars.instructions.Question = {'Paa nuvaerende tidpsunkt, hvor staerk er den staerkeste BRAENDENDE foelelse?',...
                                'Paa nuvaerende tidpsunkt, hvor BRAENDENDE foeles stimulutionen?',...
                                'Paa nuvaerende tidpsunkt, hvor VARM foeles stimulutionen?',...
                                'Paa nuvaerende tidpsunkt, hvor KOLD foeles stimulutionen?' }; 
                           
vars.instructions.QuestionCode = [1 2 3 4]; % 1 - initial burn, 2 - burning, 3 - warm, 4 - cold
vars.instructions.whichQuestion = [1 1 1 1]; %Enable or disable question (1 = enabled) %% not sure this works, needs fixing!

vars.instructions.whichKey = {'LR','UD'}; % Left/Right. Up/Down. If you are using the mouse as an input device let this entirely as LR
      
vars.instructions.ThermodeSwitch = 2:vars.task.NTrialsChange:(vars.task.NBlocksTotal*16); %When to ask participant to change thermode position (starting from 2)
vars.instructions.Thermode = 'Vent venligst, imens vi rykker rundt på apparatet. Tryk på en tast, når det er gjort.';

vars.instructions.ConfEndPoints = {'Overhovedet ikke', 'Ekstremt'};    

vars.waitStim.text = 'Når nedtællingen slutter, bedes du vurdere din oplevelse/følelse. Tryk MELLEMRUM, når det er gjort.';
