---
title: "TGI Spinal Analysis Code"
author: "A.G. Mitchell"
date: "2022-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Loading libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(Rmisc)
```

# Loading data
```{r}
# paths
datPath <- '/Users/au706616/Documents/Experiments/SPINALTGI/Raw/'
anaPath <- '/Users/au706616/Documents/Experiments/SPINALTGI/Analysis/'

# Extract all .csv files and compile
filenames <- dir(datPath, recursive = TRUE, full.names = FALSE, pattern = '.csv')
# empty dataframes for data
## with new data trials file will have changed to include temperature coding!
df_trials <- read.csv(text='procedure,trial_type,arm,condition,dermatome,order,cold_probe,trial_n,coolTemp,warmTempID,manipulation')
df_VAS <- read.csv(text='VASinit,VASburn,VASwarm,VAScold,trial_n,ID,manipulation')
df_RT <- read.csv(text='RTinit,RTburn,RTwarm,RTcold,trial_n,ID,manipulation')

## Data compiling
# trial files
setwd(datPath)
for (file in filenames){
  # trial files
  if (isTRUE(substr(basename(file), 24, 24)=="t")){
    tmp <- read.csv(file)
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_trials <- rbind(df_trials, tmp)
  }
  # VAS response files
  if (isTRUE(substr(basename(file), 24, 29)=="rating")){
    tmp <- read.csv(file, header = FALSE)
    colnames(tmp) <- c('VASinit','VASburn','VASwarm','VAScold','trial_n')
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_VAS <- rbind(df_VAS, tmp)
  }
  # VAS RT files
  if (isTRUE(substr(basename(file), 24, 29)=="respti")){
    tmp <- read.csv(file, header = FALSE)
    colnames(tmp) <- c('RTinit','RTburn','RTwarm','RTcold','trial_n')
    tmp$ID <- substr(basename(file), 4, 6)
    tmp$manipulation <- substr(basename(file), 17, 19)
    df_RT <- rbind(df_RT, tmp)
  }
}

# merge all files
df_res <- merge(df_trials, df_VAS, by = c('ID','trial_n','manipulation'))
df_res <- merge(df_res, df_RT, by = c('ID','trial_n','manipulation'))

# remove participant 019, stopped testing halfway
df_res <- df_res[df_res$ID != '019' ,]
```

# Data organisation
```{r}
# recode conditions
df_res <- df_res %>%
  mutate(condition = recode(condition, '1' = 'within', '2' = 'across'),
         cold_probe = recode(cold_probe, 'C6' = 'rostral', 'T1' = 'caudal',
                             'dist' = 'distal', 'prox' = 'proximal'))
# change levels 
df_res$cold_probe <- factor(df_res$cold_probe, 
                            levels = c("caudal", "rostral", "distal", "proximal"))

# save new data-frame
fileName = paste(anaPath, 'STGI_compiled-data.csv', sep = '')
write.csv(df_res, fileName, row.names = FALSE)

# check we have 40 participants with 96 trials
id_check <- count(df_res, 'ID')
id_check
```

# Responder check
Check whether participants median burning ratings for TGI is significantly above 0
If not, flag them as a 'non-responder'
```{r}
# Calculate median burning rating for all participants
# TGI trials only
# Then flag how many are not sig > 0
df_med <- aggregate(VASburn~ID*manipulation*cold_probe*trial_type, median, data = df_res)
tgi <-  df_med %>% 
  filter(manipulation == 'TGI')
cnt <-  df_med %>% 
  filter(manipulation == 'CNT')

# identify test results where pvalue is < .05
i = 0
test = data.frame(matrix(nrow = 40, ncol = 3))
colnames(test) <- c('ID','pval','responder')
for (id in df_id$ID){
  i = i+1
  tmp1 <- tgi[tgi$ID == id ,]
  test$ID[i] <- id
  test$pval[i] <- (t.test(tmp1$VASburn, mu = 0, alternative = 'greater'))$p.value
  test$responder[i] <- isTRUE(test$pval[i] < .05)
}

# combine responder logic with main data-frame
test$responder <- ifelse(test$responder == TRUE, 1, 0)
test <- test[, c(1,3)]
df_res <- merge(df_res, test, by = 'ID')
  
# count the number of false responses
nNONRESP <- sum(test$responder == FALSE)
# print
print(paste0('Non responders: ', nNONRESP, '/', length(test$ID)))
```

# Let's look at the data!
```{r}
# Reorganise data-frame 
# pivot longer the VAS response by each quality of sensation
# do this for both RT and VAS
df_long <- df_res %>% 
  pivot_longer(cols = c(VASinit, VASburn, VASwarm, VAScold),
               names_to = 'quality',
               values_to = 'VAS')
df_long2 <- df_res %>% 
  pivot_longer(cols = c(RTinit, RTburn, RTwarm, RTcold),
               names_to = 'quality',
               values_to = 'RT')
# remove the VAS & RT from quality column
df_long$quality <- substr(df_long$quality, 4, 7)
df_long2$quality <- substr(df_long2$quality, 3, 6)
# remove columns from both then merge
df_long <- df_long[, c(1:12,17:19)]
df_long2 <- df_long2[, c(1:12,17:19)]
df_long <- merge(df_long, df_long2)

# then remove NaNs
df_long <- df_long %>% filter(!is.na(VAS))
# remove the initial trials - not important for now
init_burn <- filter(df_long, quality == 'init')
all_vas <- filter(df_long, quality != 'init')
# order the labelling of quality so it is cold, warm, burn

# plot distribution of data
ggplot(all_vas) +
  geom_density(aes(VAS, colour = manipulation)) +
  facet_wrap(~quality, scales = "free") +
  theme_bw()
```
# MAIN HYPOTHESES
# Plot descriptives for each hypotheses
Hypothesis 1: within vs. across dermatomes

```{r}
# calculate means
vas_meds <- aggregate(VAS ~ quality*manipulation*cold_probe*ID, median, data = all_vas)
vas_h1 <- aggregate(VAS)
# then plot :D
blue <- brewer.pal(6, "Blues")
grey <- brewer.pal(6, "Greys")

ggplot(vas_meds, aes(cold_probe, VAS, colour = manipulation, group = ID)) +
  geom_point(position = position_dodge(.2)) +
  facet_grid(~quality*manipulation) +
  scale_colour_manual(values = c(grey[3], blue[4])) +
  theme_bw()
```

Hypothesis 2 a & b: relative location of warm and cold
